name: Bug Report
description: Something isn't working quite right in M12Labs.
labels: [bug, not confirmed]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Bug reports should only be used for reporting issues with how the panel works.
        > For general help or support, please visit our [Discord](https://discord.gg/fVJZtqKYrc).

  - type: checkboxes
    attributes:
      label: Pre-flight Checklist
      options:
        - label: I have searched the existing issues and confirmed this has not been reported before.
          required: true
        - label: I believe this is a bug with the software, not a configuration issue with my system.
          required: true

  - type: textarea
    attributes:
      label: What's Happening
      description: A clear and concise description of the bug you are experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >
        Provide detailed step-by-step instructions to reproduce the issue.
        Issues without clear reproduction steps may be closed without investigation.
    validations:
      required: true

  - type: input
    id: panel-version
    attributes:
      label: Panel Version
      description: The version of M12Labs you are running. "Latest" is not a version.
      placeholder: 2.0.0-alpha-2.7
    validations:
      required: true

  - type: input
    id: wings-version
    attributes:
      label: Wings Version
      description: The version of Wings you are running. "Latest" is not a version.
      placeholder: 1.4.2
    validations:
      required: false

  - type: checkboxes
    id: extensions-installed
    attributes:
      label: Extensions Installed
      description: Are you running any M12Labs extensions?
      options:
        - label: "Yes, I have extensions installed."

  - type: textarea
    id: extensions-list
    attributes:
      label: Extensions List
      description: If yes above, please list the extensions and their versions.
      placeholder: "ExtensionA v1.0, ExtensionB v2.3"
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Paste any relevant error logs here.
      render: bash
    validations:
      required: false

  - type: textarea
    id: extra-comments
    attributes:
      label: Additional Comments
      description: Anything else that may help diagnose this issue?
    validations:
      required: false