<?php

namespace Everest\Http\Controllers\Api\Application\Billing;

use Carbon\Carbon;
use Everest\Facades\Activity;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Response;
use Everest\Models\Billing\Product;
use Everest\Models\Billing\Category;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Everest\Services\Billing\BillingConfigImportService;
use Everest\Http\Controllers\Api\Application\ApplicationApiController;
use Everest\Http\Requests\Api\Application\Billing\Config\ExportBillingConfigRequest;
use Everest\Http\Requests\Api\Application\Billing\Config\ImportBillingConfigRequest;

class ConfigController extends ApplicationApiController
{
    /**
     * ConfigController constructor.
     */
    public function __construct(
        private BillingConfigImportService $importService,
    ) {
        parent::__construct();
    }

    /**
     * Export the linked categories and products on this Panel.
     *
     * @throws \Throwable
     */
    public function export(ExportBillingConfigRequest $request): StreamedResponse
    {
        $data = [
            'export_info' => [
                'warning' => 'This file was automatically generated by M12Labs v4. Do NOT edit this file unless you know what you are doing.',
                'requested_by' => (string) $request->user()->uuid,
                'requested_at' => (string) Carbon::now(),
            ],
            'categories' => Category::all(),
            'products' => Product::with('billingCycles')->get(),
        ];

        Activity::event('admin:billing:config:export')
            ->description('User exported M12Labs billing configuration')
            ->log();

        return response()->stream(function () use ($data) {
            echo json_encode($data, JSON_PRETTY_PRINT);
        }, 200, [
            'Content-Type' => 'application/json',
            'Content-Disposition' => 'attachment; filename="data.json"',
        ]);
    }

    /**
     * Import a billing configuration file to M12Labs.
     *
     * @throws \Throwable
     */
    public function import(ImportBillingConfigRequest $request): Response|JsonResponse
    {
        $data = (array) $request->input('data');
        $override = (bool) $request->input('override');
        $ignore_duplicates = (bool) $request->input('ignore_duplicates');
        $resolution = (array) $request->input('resolution', []);

        $importOptionsIgnoreDuplicates = $override ? false : $ignore_duplicates;
        $analysis = $this->importService->analyze($data, $importOptionsIgnoreDuplicates, $resolution);

        if (!empty($analysis['conflicts'])) {
            return response()->json([
                'object' => 'billing_import_conflict',
                'attributes' => [
                    'conflicts' => $analysis['conflicts'],
                    'available_nests' => $analysis['available_nests'],
                ],
            ], 409);
        }

        if ($override) {
            Category::query()->delete();
            Product::query()->delete();
        }

        $this->importService->persist($analysis['data'], $importOptionsIgnoreDuplicates);

        Activity::event('admin:billing:config:import')
            ->property('override', $override)
            ->property('ignore_duplicates', $ignore_duplicates)
            ->description('User imported M12Labs billing configuration')
            ->log();

        return $this->returnNoContent();
    }
}
